# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - '*'
    paths:
      - '*.ts'
      - '*.json'
      - .github/workflows/npm-publish.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '*.ts'
      - '*.json'
      - .github/workflows/npm-publish.yml
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: current
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install

      - name: Check code style
        run: |
          pnpm run lint

      - name: Build
        run: |
          pnpm build
          pnpm pack

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: 'vite-plugin-build-id-*.tgz'

      - name: Publish to npm
        if: github.event_name == 'release'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
